-- Create sessions table
CREATE TABLE IF NOT EXISTS sessions (
  id TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  date DATE NOT NULL,
  location TEXT NOT NULL,
  wind INTEGER,
  duration INTEGER,
  rating INTEGER,
  wing TEXT,
  board TEXT,
  mast TEXT,
  notes TEXT,
  user_id UUID REFERENCES auth.users NOT NULL
);

-- Create gear table
CREATE TABLE IF NOT EXISTS gear (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  size TEXT,
  type TEXT NOT NULL, -- 'wings', 'boards', 'masts'
  user_id UUID REFERENCES auth.users NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE gear ENABLE ROW LEVEL SECURITY;

-- Policies for sessions
CREATE POLICY "Users can create their own sessions." ON sessions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own sessions." ON sessions
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own sessions." ON sessions
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own sessions." ON sessions
  FOR DELETE USING (auth.uid() = user_id);

-- Policies for gear
CREATE POLICY "Users can create their own gear." ON gear
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own gear." ON gear
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own gear." ON gear
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own gear." ON gear
  FOR DELETE USING (auth.uid() = user_id);
